### ISSUE TITLE
Create serializer for Organizer model

### ISSUE THREAD

**Issue by gaurKrishna** [iiitv/arcadia-backend#7]
Create a serializer for the organizer model to be used by the corresponding Organizer viewset. For reference check out Django rest frameworks documentation on [model serializer](https://www.django-rest-framework.org/api-guide/serializers/#modelserializer).

**Comment by rexdivakar** [comment]
Hey @gaurKrishna i would love to help in this can u please assign it

**Comment by gaurKrishna** [comment]
> Hey @gaurKrishna i would love to help in this can u please assign it

Go for it 👍

**Comment by rexdivakar** [comment]
May i know what kind of endpoints are you looking in views.py ?
